os: osx
osx_image: xcode10.2
language: swift
install:
- sudo gem install xcpretty-travis-formatter
script:
- .bin/tests

notifications:
  email: false
  slack:
    rooms:
      secure: qka13hJ5hvU25l6BIU1dOnaPo4N3KNvwTBr76oLUT0wYzHz1aTfsx++hvtx4CQbfRjxzGmIlwfSXt7rl7x1yP1FxeApaLsXuUN5V0S32SXom4225Mmh7VeDwFXLij+aafUsNkMSKNSdTtUNQx3flMJvQbSM4nH2xsOODLwhRAs18vkitpnKhVP9MkLY9Lx5mPwkf/MqyrvaAjq8XKFK7QjqgqVRhuHyOU0BgZs3dV1URh/jjG1hytUnydxF8dm6lQYHj0akpM1hFkH4kTqdFDPEeq9igtWiJjNl5RUk4MjSQg/xqtmADUrM7UtiP0B/A5z/98VASSiZhYBggT+0Sm9bys0Q8cExIZPgHUUZnHj60SDhHMQMpGcz1i6q0qsNPBi17/OJt3ETa4Ixr+IA+f3aWVOM9us3BqezldxgizDZnyHFkiK7kzTI2BFwnRdew709aMHkr1Fa6GTaYUgj0rTiYkGVP5+1E4KCn0qjpbkkWQ8qgIpHTDz2iM20e11G4d1KsVpRSlEOHJ1LOWaR8y01Iso+K9n+KHpKCVfpxHcG0uAJmOVEWV4viodGRZVyoIGilUzFeMeMaGR5fpSLF8AANNZee44JSGpr0aJiAotP3NjNRNCeXc1bUcrAStmWP77He8AAE8ZdWi4CWHFBQVC+52CI3kNqvcnww5ohthb4=
