#!/bin/sh


echo
echo "Testing Mac"
rm -rf .build/Mac.xcresult .build/Mac.log
set -o pipefail && xcodebuild clean test -workspace BookishModel.xcworkspace -scheme BookishModelMac -enableCodeCoverage YES -resultBundlePath .build/Mac.xcresult | tee .build/Mac.log | xcpretty -f `xcpretty-travis-formatter`
MAC_RESULT=$?

echo
echo "Testing Mobile"

rm -rf .build/Mobile.xcresult .build/Mobile.log
set -o pipefail && xcodebuild clean test -workspace BookishModel.xcworkspace -scheme BookishModelMobile -destination "name=iPad Pro (11-inch)" -enableCodeCoverage YES -resultBundlePath .build/Mobile.xcresult | tee .build/Mobile.log | xcpretty -f `xcpretty-travis-formatter`
MOBILE_RESULT=$?

echo
echo "Coverage"

.bin/coverage
COVERAGE_RESULT=$?

echo
echo Done

if [[ ($MAC_RESULT != 0) || ($MOBILE_RESULT != 0) || ($COVERAGE_RESULT != 0) ]]
then
    echo "Tests failed."
    exit 1
fi
